import {
  airpodsPro,
  applePencil,
  appleTv,
  headPhone,
  ipad1,
  ipad2,
  iphone14,
  iphone15,
  iphone15Blue,
  mackbook1,
  mackbook2,
  mackbook3,
  silverRiser,
  watch1,
  watch2,
  shops1,
  shops2,
  shops3,
  shops4,
  shops5,
  shops6,
  shops7,
  shops8,
  shops9,
  shops10,
  discount1,
  discount2,
  discount3,
  discount4,
  discount5,
  discount6,
  discount7,
  discount8,
  discount9,
} from "./assets";

import { BiBox, BiDollarCircle, BiHeadphone, BiWallet } from "react-icons/bi";
// export const Data = {
//   Products: [
//     {
//       id: 1,
//       discount: 50,
//       cover: ipad1,
//       name: "Apple Ipad gray",
//       price: 750,
//       reviews: "(123 reviews)",
//       categories: "i-pads",
//     },
//     {
//       id: 2,
//       discount: 40,
//       cover: ipad2,
//       name: "Apple Ipad blue",
//       price: 1000,
//       reviews: "(123 reviews)",
//       categories: "Ipads",
//     },
//     {
//       id: 3,
//       discount: 40,
//       cover: ipad1,
//       name: "Apple Ipad pro",
//       price: 560,
//       reviews: "(123 reviews)",
//       categories: "Ipads",
//     },
//     {
//       id: 4,
//       discount: 40,
//       cover: ipad2,
//       name: "Apple Ipad Night",
//       price: 700,
//       reviews: "(123 reviews)",
//       categories: "Ipads",
//     },
//     {
//       id: 5,
//       discount: 50,
//       cover: headPhone,
//       name: "Night headsets",
//       price: 600,
//       categories: "headphones",
//     },
//     {
//       id: 6,
//       discount: 50,
//       cover: appleTv,
//       name: "Apple Tv",
//       price: 2200,
//       reviews: "(123 reviews)",
//       categories: "tv",
//     },
//     {
//       id: 7,
//       discount: 50,
//       cover: applePencil,
//       name: "Apple pencil",
//       price: 730,
//       categories: "pencil",
//     },
//     {
//       id: 8,
//       discount: 30,
//       cover: watch2,
//       name: "Apple watch blue",
//       price: 400,
//       categories: "watch",
//     },
//     {
//       id: 9,
//       discount: 50,
//       cover: watch1,
//       name: "Apple watch gray",
//       price: 550,
//       reviews: "(123 reviews)",
//       categories: "watch",
//     },
//     {
//       id: 10,
//       discount: 10,
//       cover: mackbook1,
//       name: "macbook pro",
//       price: 1400,
//       reviews: "(123 reviews)",
//       categories: "Laptops",
//     },
//     {
//       id: 11,
//       discount: 20,
//       cover: mackbook2,
//       name: "macbook blue",
//       price: 1200,
//       reviews: "(123 reviews)",
//       categories: "Laptops",
//     },
//     {
//       id: 12,
//       discount: 50,
//       cover: mackbook3,
//       name: "macbook m2",
//       price: 1100,
//       reviews: "(123 reviews)",
//       categories: "Laptops",
//     },
//     {
//       id: 13,
//       discount: 70,
//       cover: silverRiser,
//       name: "Silver riser",
//       price: 100,
//       reviews: "(123 reviews)",
//       categories: "riser",
//     },
//     {
//       id: 14,
//       discount: 40,
//       cover: airpodsPro,
//       name: "Air Pods Pro",
//       price: 100,
//       reviews: "(123 reviews)",
//       categories: "pods",
//     },
//     {
//       id: 15,
//       discount: 50,
//       cover: airpodsPro,
//       name: "Air Pods Twin max",
//       price: 100,
//       reviews: "(123 reviews)",
//       categories: "pods",
//     },
//     {
//       id: 16,
//       discount: 50,
//       cover: iphone14,
//       name: "Iphone 14",
//       price: 100,
//       reviews: "(123 reviews)",
//       categories: "phone",
//     },
//     {
//       id: 17,
//       discount: 50,
//       cover: iphone15,
//       name: "Iphone 15",
//       price: 100,
//       reviews: "(123 reviews)",
//       categories: "phone",
//     },
//     {
//       id: 18,
//       discount: 50,
//       cover: iphone15Blue,
//       name: "Iphone 15 blue",
//       price: 100,
//       reviews: "(123 reviews)",
//       categories: "phone",
//     },
//   ],
// };

export const Data = {
  Products: [
    {
      id: 1,
      discount: 50,
      cover: shops1,
      name: "Apple Ipad gray",
      price: 750,
      reviews: "(123 reviews)",
      categories: "Ipads",
    },
    {
      id: 2,
      discount: 40,
      cover: shops2,
      name: "Apple Ipad blue",
      price: 1000,
      reviews: "(123 reviews)",
      categories: "Ipads",
    },
    {
      id: 3,
      discount: 40,
      cover: shops3,
      name: "Apple Ipad pro",
      price: 560,
      reviews: "(123 reviews)",
      categories: "Ipads",
    },
    {
      id: 4,
      discount: 40,
      cover: shops4,
      name: "Apple Ipad Night",
      price: 700,
      reviews: "(123 reviews)",
      categories: "Ipads",
    },
    {
      id: 5,
      discount: 50,
      cover: shops5,
      name: "Night headsets",
      price: 600,
      categories: "Headphones",
    },
    {
      id: 6,
      discount: 50,
      cover: discount9,
      name: "Apple Tv",
      price: 2200,
      reviews: "(123 reviews)",
      categories: "Tv and Home",
    },
    {
      id: 7,
      discount: 50,
      cover: shops7,
      name: "Apple pencil",
      price: 730,
      categories: "Pencil",
    },
    {
      id: 8,
      discount: 30,
      cover: shops8,
      name: "Apple watch blue",
      price: 400,
      categories: "Watch",
    },
    {
      id: 9,
      discount: 50,
      cover: shops9,
      name: "Apple watch gray",
      price: 550,
      reviews: "(123 reviews)",
      categories: "Watch",
    },
    {
      id: 10,
      discount: 10,
      cover: discount1,
      name: "macbook pro",
      price: 1400,
      reviews: "(123 reviews)",
      categories: "Laptops",
    },
    {
      id: 11,
      discount: 20,
      cover: discount2,
      name: "macbook blue",
      price: 1200,
      reviews: "(123 reviews)",
      categories: "Laptops",
    },
    {
      id: 12,
      discount: 50,
      cover: discount3,
      name: "macbook m2",
      price: 1100,
      reviews: "(123 reviews)",
      categories: "Laptops",
    },
    {
      id: 13,
      discount: 50,
      cover: shops10,
      name: "macbook m3",
      price: 1100,
      reviews: "(123 reviews)",
      categories: "Laptops",
    },
    // {
    //   id: 14,
    //   discount: 70,
    //   cover: silverRiser,
    //   name: "Silver riser",
    //   price: 100,
    //   reviews: "(123 reviews)",
    //   categories: "riser",
    // },
    // {
    //   id: 14,
    //   discount: 40,
    //   cover: airpodsPro,
    //   name: "Air Pods Pro",
    //   price: 100,
    //   reviews: "(123 reviews)",
    //   categories: "pods",
    // },
    // {
    //   id: 15,
    //   discount: 50,
    //   cover: airpodsPro,
    //   name: "Air Pods Twin max",
    //   price: 100,
    //   reviews: "(123 reviews)",
    //   categories: "pods",
    // },
    // {
    //   id: 16,
    //   discount: 50,
    //   cover: iphone14,
    //   name: "Iphone 14",
    //   price: 100,
    //   reviews: "(123 reviews)",
    //   categories: "phone",
    // },
    // {
    //   id: 17,
    //   discount: 50,
    //   cover: iphone15,
    //   name: "Iphone 15",
    //   price: 100,
    //   reviews: "(123 reviews)",
    //   categories: "phone",
    // },
    // {
    //   id: 18,
    //   discount: 50,
    //   cover: iphone15Blue,
    //   name: "Iphone 15 blue",
    //   price: 100,
    //   reviews: "(123 reviews)",
    //   categories: "phone",
    // },
  ],
  Collections: [
    {
      id: 1,
      discount: 50,
      cover: discount1,
      name: "Apple Ipad gray",
      price: 750,
      reviews: "(123 reviews)",
      categories: "Ipads",
    },
    {
      id: 2,
      discount: 40,
      cover: discount2,
      name: "Apple Ipad blue",
      price: 1000,
      reviews: "(123 reviews)",
      categories: "Ipads",
    },
    {
      id: 3,
      discount: 40,
      cover: discount3,
      name: "Apple Ipad pro",
      price: 560,
      reviews: "(123 reviews)",
      categories: "Ipads",
    },
    {
      id: 4,
      discount: 40,
      cover: discount4,
      name: "Apple Ipad Night",
      price: 700,
      reviews: "(123 reviews)",
      categories: "Ipads",
    },
    {
      id: 5,
      discount: 50,
      cover: discount5,
      name: "Night headsets",
      price: 600,
      categories: "Headphones",
    },
    {
      id: 6,
      discount: 50,
      cover: discount9,
      name: "Apple Tv",
      price: 2200,
      reviews: "(123 reviews)",
      categories: "Tv and Home",
    },
    {
      id: 7,
      discount: 50,
      cover: discount6,
      name: "Apple pencil",
      price: 730,
      categories: "Pencil",
    },
    {
      id: 8,
      discount: 30,
      cover: discount7,
      name: "Apple watch blue",
      price: 400,
      categories: "Watch",
    },
    {
      id: 9,
      discount: 50,
      cover: discount8,
      name: "Apple watch gray",
      price: 550,
      reviews: "(123 reviews)",
      categories: "Watch",
    },
    {
      id: 10,
      discount: 10,
      cover: discount1,
      name: "macbook pro",
      price: 1400,
      reviews: "(123 reviews)",
      categories: "Laptops",
    },
    {
      id: 11,
      discount: 20,
      cover: discount2,
      name: "macbook blue",
      price: 1200,
      reviews: "(123 reviews)",
      categories: "Laptops",
    },
    {
      id: 12,
      discount: 50,
      cover: discount3,
      name: "macbook m2",
      price: 1100,
      reviews: "(123 reviews)",
      categories: "Laptops",
    },
    {
      id: 13,
      discount: 50,
      cover: discount9,
      name: "macbook m3",
      price: 1100,
      reviews: "(123 reviews)",
      categories: "Laptops",
    },
  ],
};

export const categoryData = [
  { name: "Ipads", image: shops1, id: 1 },
  { name: "Headphones", image: shops2, id: 2 },
  { name: "Tv and Home", image: shops3, id: 3 },
  { name: "Pencil", image: shops4, id: 4 },
  { name: "Watch", image: shops5, id: 5 },
  { name: "Laptops", image: shops7, id: 6 },
];

export const bannerTexts = [
  {
    title: "Free Shipping",
    sub: "Free shipping for order above $20,000",
    icon: <BiBox />,
  },
  {
    title: "Money Guarantee",
    sub: "Within 30 days for an exchange",
    icon: <BiDollarCircle />,
  },
  {
    title: "Online Support",
    sub: "24 hours a day, 7 days a week",
    icon: <BiHeadphone />,
  },
  {
    title: "Flexible Payment",
    sub: "Pay with multiple cards",
    icon: <BiWallet />,
  },
];
